builders:
  model_builder:
    import: "package:typesafe_firebase/functions/builder.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: {".dart": [".model_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
  registration_builder:
    import: "package:typesafe_firebase/functions/builder.dart"
    builder_factories: ["registrationBuilder"]
    build_extensions: {r"$package$": ["models.g.dart"]}
    auto_apply: none
    required_inputs: [".model_builder.g.part"]
    build_to: source
    defaults:
      options:
        input_pattern: "lib/**/*.model_builder.g.part"
        output_path: "lib/models.g.dart"

targets:
  $default:
    sources:
      - examples/**
      - lib/**
      - $package$
      - pubspec.yaml
      - test/**
    builders:
      json_serializable:
        generate_for:
          - examples/**.dart
      typesafe_firebase:model_builder:
        generate_for:
          - examples/**.dart
      typesafe_firebase:registration_builder:
        enabled: true
        options:
          input_pattern: "examples/**.model_builder.g.part"
          output_path: "examples/generated/models.g.dart"
      mockito|mockBuilder:
        generate_for:
          - test/**_test.dart 
        options:
          build_extensions:
            '^test/{{}}.dart': 'test/mocks/{{}}.mocks.dart'
