builders:
  model_builder:
    import: "package:typesafe_firebase_generator/typesafe_firebase_generator.dart"
    builder_factories: ["modelBuilder"]
    build_extensions: {".dart": [".model_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  schema_builder:
    import: "package:typesafe_firebase_generator/typesafe_firebase_generator.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".dart": [".schema_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
  registration_builder:
    import: "package:typesafe_firebase_generator/typesafe_firebase_generator.dart"
    builder_factories: ["registrationBuilder"]
    build_extensions: {r"$package$": ["models.g.dart"]}
    auto_apply: none
    required_inputs: [".model_builder.g.part"]
    build_to: source
    defaults:
      options:
        input_pattern: "lib/**/*.model_builder.g.part"
        output_path: "lib/register_models.g.dart"

